---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/cp maintenance/index.html $DEPLOYPATH
    - /bin/cp maintenance/.htaccess $DEPLOYPATH
    - /bin/cp maintenance/sanaa-logo-640.png $DEPLOYPATH
    - /bin/cp maintenance/maintenance-hero.jpg $DEPLOYPATH
